name: discovery-utils
recipe: lamp
env_file:
  - defaults.env
config:
  webroot: ./public
  php: '7.4'
  composer_version: '1.10.21'
services:
  appserver:
    run_as_root:
      - apt-get update -y
tooling:
  build:
    description: Manually invokes all our build steps
    cmd:
      - appserver: composer install
  test:
    description: run all our tests
    cmd:
      - appserver: php bin/phpunit
