name: discovery-utils
recipe: lamp
env_file:
  - defaults.env
config:
  webroot: .
  php: '7.2'
services:
  appserver:
    run_as_root:
      - apt-get update -y
tooling:
  build:
    description: Manually invokes all our build steps
    cmd:
      - appserver: composer install
  test:
    description: run all our tests 
    cmd:
      - appserver: php bin/phpunit
